map $http_upgrade $connection_upgrade {
    default  "";
    websocket "upgrade";
}

server {
    listen 80;
    server_name _;

    # 헬스체크 – 백엔드 검증형 예시
    location /health {
        proxy_pass http://docker/health;
        access_log off;
    }

  if ($http_x_forwarded_proto = "http") {
    return 301 https://$host$request_uri;
  }

    # 앱 트래픽
    location / {
        proxy_pass http://docker;
        proxy_http_version 1.1;
        proxy_set_header Upgrade          $http_upgrade;
        proxy_set_header Connection       $connection_upgrade;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
