upstream spring_boot {
    server 127.0.0.1:8080 fail_timeout=0;
}

server {
    listen       80 default_server;
    server_name  dev.catdogeats.kro.kr;

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    # preflight(OPTIONS) 요청에 대한 빠른 응답
    if ($request_method = 'OPTIONS') {
        # 204 No Content 반환
        add_header 'Content-Length' 0;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        return 204;
    }

    # 모든 요청을 Spring Boot 로 전달
    location / {
        proxy_pass         http://spring_boot;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
