name: Deploy to Elastic Beanstalk

on:
  workflow_run:
    workflows: ["Build & Publish Docker image"]
    types: [completed]
  workflow_dispatch:
    inputs:
      source_sha:
        description: 'Build SHA to deploy'
        required: true
permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download image info artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-info
          path: .

      - name: Load image variables
        run: |
          IMAGE=$(sed -n '1p' image_info.txt)
          IMAGE_LATEST=$(sed -n '2p' image_info.txt)
          echo "IMAGE=${IMAGE}"         >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE_LATEST}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: 로그인 to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 리포지토리명 소문자 변환 & 태그 변수 설정
        run: |
          REPO_LOWER=${GITHUB_REPOSITORY,,}
          echo "REPO_LOWER=${REPO_LOWER}"            >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${REPO_LOWER}:${GITHUB_SHA}"     >> $GITHUB_ENV
          echo "IMAGE_LATEST=ghcr.io/${REPO_LOWER}:latest"     >> $GITHUB_ENV

      - name: Prepare Dockerrun
        run: |
          cat > Dockerrun.aws.json <<EOF
          {
          "AWSEBDockerrunVersion": 2,
          "image": {
           "name": "${{ env.IMAGE_LATEST }}",
           "update": true
          },
          "ports": [{"containerPort": 8080}],
          "logging": "/var/log/nginx"
          }
          EOF

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key:    ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws_secret_key:    ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          region:            ap-northeast-2
          application_name:  aibe1-team05
          environment_name:  aibe1-team05-env
          version_label:     deploy-${{ github.run_number }}
          deployment_package: Dockerrun.aws.json
          wait_for_environment_recovery: 120
